### PR TITLE
Remove conflict definition

### PR DESCRIPTION
**Pull request by Propaganistas**
See https://github.com/giggsey/libphonenumber-for-php/pull/625

### CODE REVIEW

**Comment by Propaganistas** [comment]
@giggsey Not sure why the PHPStan workflow is failing during checkout. You might want to rerun the job manually.

**Comment by Propaganistas** [comment]
I think you should remove the following lines from the SAST workflow. It makes PRs from forks fail.

https://github.com/giggsey/libphonenumber-for-php-lite/blob/feef98fb9ee2c7bc6c689a007ad38ccc8569486f/.github/workflows/sast.yml#L19-L20

**Comment by giggsey** [comment]
> I think you should remove the following lines from the SAST workflow. It makes PRs from forks fail.
> 
> https://github.com/giggsey/libphonenumber-for-php-lite/blob/feef98fb9ee2c7bc6c689a007ad38ccc8569486f/.github/workflows/sast.yml#L19-L20

Can you remove that uses section? I don't have permission to push to your branch

**Comment by Propaganistas** [comment]
done, but i'm unsure which workflow will be run. I would assume that the original repo's workflow will be run to avoid security issues.

**Comment by giggsey** [comment]
Thanks, that's fine. If it fails again, I'll force merge.

**Comment by Propaganistas** [comment]
@giggsey Sorry to revisit this. Last night I was thinking it might be better to set the conflict configuration to the following:

```
"conflict": {
   "giggsey/libphonenumber-for-php": "<8.13.35"
}
```

Brain dump:
* Whenever lite gets installed with a version <= 8.13.34, the conflict config is still there, so it'll conflict with any main package's version. We can't really help that situation (conflict takes precedence) besides forcing the dev to update lite.
* As soon as lite gets installed starting from the new version (8.13.35 - to be released):
    * Starting from main package version 8.13.35 (to be released), the `replace` config is in place so everything will work as expected
    *  if main package's version is <= 8.13.34, there's no `replace` config in those old versions. But lite will gladly install because the conflict config is now gone.... causing namespace overlap.

**Comment by giggsey** [comment]
I've 'successfully' installed this together, which proves your problem:

```json
{
    "require": {
        "giggsey/libphonenumber-for-php-lite": "dev-main as 8.13.35",
        "giggsey/libphonenumber-for-php": "^8.13"
    }
}
```

With #54, dev-conflict for lite gives a composer error.

Replacing the composer.json with:


```json
{
    "require": {
        "giggsey/libphonenumber-for-php-lite": "dev-conflict as 8.13.35",
        "giggsey/libphonenumber-for-php": "dev-master as 8.13.35"
    }
}
```

still errors:

>    - Root composer.json requires giggsey/libphonenumber-for-php-lite dev-conflict as 8.13.35 -> satisfiable by giggsey/libphonenumber-for-php-lite[dev-conflict].
>    - Only one of these can be installed: giggsey/libphonenumber-for-php[dev-master], giggsey/libphonenumber-for-php-lite[dev-conflict]. giggsey/libphonenumber-for-php replaces giggsey/libphonenumber-for-php-lite and thus cannot coexist with it.
>    - Root composer.json requires giggsey/libphonenumber-for-php dev-master as 8.13.35 -> satisfiable by giggsey/libphonenumber-for-php[dev-master].


I'll try to read the composer docs over the next few days.

**Comment by Propaganistas** [comment]
@giggsey 

I did some more investigation. It appears that `replace` takes precedence over `conflict` - sorry for the confusion earlier.
In that regard, the `conflict` configuration is quite crucial (see tables below), but I think it doesn't matter how it gets configured (`*` or `<8.13.35`). As long as it's there in some way so it'll error out for older versions of the main package. So I guess it can be set to whatever you feel most comfortable with...

Sorry for the misdirecting OP/PR. I've learned about composer internals myself now!

| main | lite | result |
|--------|--------|--------|
| < 8.13.35 | without conflict | double install - NOK  |
| >= 8.13.35 | without conflict | replace kicks in - single install of main - OK |

| main | lite | result |
|--------|--------|--------|
| < 8.13.35 | with conflict | conflict error - OK  |
| >= 8.13.35 | with conflict | replace kicks in - single install of main - OK |

**Comment by Propaganistas** [comment]
> Just so i'm clear, we need to add the conflict back (#54) to lite? 

Correct. Sorry for the hassle

**Comment by giggsey** [comment]
Thanks @Propaganistas - I'll change it to * in case of version number weirdness

**Pull request merged**
